# Generated by Django 4.0.1 on 2022-01-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
                ('number', models.SmallIntegerField(verbose_name='Число')),
            ],
        ),
        migrations.CreateModel(
            name='PsychicNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=50)),
                ('number', models.SmallIntegerField()),
                ('is_checked', models.BooleanField(default=False)),
                ('confidence_level', models.IntegerField(default=0)),
                ('psychic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychic', to='psychic_test.physic')),
            ],
        ),
    ]
