# Generated by Django 4.0.1 on 2022-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychic_test', '0002_psychicnumbers_confidence_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychicnumbers',
            name='confidence_level',
            field=models.IntegerField(default=0),
        ),
    ]
