# Generated by Django 4.0.1 on 2022-01-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychic_test', '0003_alter_psychicnumbers_confidence_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychicnumbers',
            name='user_attempt',
        ),
        migrations.RemoveField(
            model_name='usernumbers',
            name='user_attempt',
        ),
    ]
