# Generated by Django 4.0.1 on 2022-01-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychic_test', '0004_remove_psychicnumbers_user_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychicnumbers',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
