# Generated by Django 4.0.1 on 2022-01-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychic_test', '0007_remove_psychicnumbers_is_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychicnumbers',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernumbers',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
